version: '3.9'

services:

  pearls_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: pearls_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root